src/java/JsfClass/Order1Controller.java
package JsfClass;

import JsfClass.*;
import Entity.Order1;
import JsfClass.util.JsfUtil;
import JsfClass.util.JsfUtil.PersistAction;
import SessionBean.Order1Facade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("order1Controller")
@SessionScoped
public class Order1Controller implements Serializable {

    @EJB
    private SessionBean.Order1Facade ejbFacade;
    private List<Order1> items = null;
    private Order1 selected;

    public Order1Controller() {
    }

    public Order1 getSelected() {
        return selected;
    }

    public void setSelected(Order1 selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private Order1Facade getFacade() {
        return ejbFacade;
    }

    public Order1 prepareCreate() {
        selected = new Order1();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle3").getString("Order1Created"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle3").getString("Order1Updated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle3").getString("Order1Deleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Order1> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle3").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle3").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Order1 getOrder1(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Order1> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Order1> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Order1.class)
    public static class Order1ControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            Order1Controller controller = (Order1Controller) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "order1Controller");
            return controller.getOrder1(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Order1) {
                Order1 o = (Order1) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Order1.class.getName()});
                return null;
            }
        }

    }

}

web/Admin/order1/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="Order1CreateDlg" widgetVar="Order1CreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle3.CreateOrder1Title}">
            <h:form id="Order1CreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{order1Controller.selected != null}">
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_id}" for="id" />
                        <p:inputText id="id" value="#{order1Controller.selected.id}" title="#{bundle3.CreateOrder1Title_id}" required="true" requiredMessage="#{bundle3.CreateOrder1RequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_company}" for="company" />
                        <p:inputText id="company" value="#{order1Controller.selected.company}" title="#{bundle3.CreateOrder1Title_company}" required="true" requiredMessage="#{bundle3.CreateOrder1RequiredMessage_company}"/>
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_name}" for="name" />
                        <p:inputText id="name" value="#{order1Controller.selected.name}" title="#{bundle3.CreateOrder1Title_name}" />
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_mobile}" for="mobile" />
                        <p:inputText id="mobile" value="#{order1Controller.selected.mobile}" title="#{bundle3.CreateOrder1Title_mobile}" required="true" requiredMessage="#{bundle3.CreateOrder1RequiredMessage_mobile}"/>
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_email}" for="email" />
                        <p:inputText id="email" value="#{order1Controller.selected.email}" title="#{bundle3.CreateOrder1Title_email}" required="true" requiredMessage="#{bundle3.CreateOrder1RequiredMessage_email}"/>
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_address}" for="address" />
                        <p:inputText id="address" value="#{order1Controller.selected.address}" title="#{bundle3.CreateOrder1Title_address}" />
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_phone}" for="phone" />
                        <p:inputText id="phone" value="#{order1Controller.selected.phone}" title="#{bundle3.CreateOrder1Title_phone}" required="true" requiredMessage="#{bundle3.CreateOrder1RequiredMessage_phone}"/>
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_activityCompany}" for="activityCompany" />
                        <p:inputText id="activityCompany" value="#{order1Controller.selected.activityCompany}" title="#{bundle3.CreateOrder1Title_activityCompany}" />
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_describtion}" for="describtion" />
                        <p:inputText id="describtion" value="#{order1Controller.selected.describtion}" title="#{bundle3.CreateOrder1Title_describtion}" />
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_updatedAt}" for="updatedAt" />
                        <p:calendar id="updatedAt" pattern="MM/dd/yyyy HH:mm:ss" value="#{order1Controller.selected.updatedAt}" title="#{bundle3.EditOrder1Title_updatedAt}"  showOn="button"/>
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_createdAt}" for="createdAt" />
                        <p:calendar id="createdAt" pattern="MM/dd/yyyy HH:mm:ss" value="#{order1Controller.selected.createdAt}" title="#{bundle3.EditOrder1Title_createdAt}"  showOn="button"/>
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_productId}" for="productId" />
                        <p:selectOneMenu id="productId" value="#{order1Controller.selected.productId}" >
                            <f:selectItems value="#{productController.itemsAvailableSelectOne}"
                                           var="productIdItem"
                                           itemValue="#{productIdItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_cityId}" for="cityId" />
                        <p:selectOneMenu id="cityId" value="#{order1Controller.selected.cityId}" >
                            <f:selectItems value="#{cityController.itemsAvailableSelectOne}"
                                           var="cityIdItem"
                                           itemValue="#{cityIdItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle3.CreateOrder1Label_brandId}" for="brandId" />
                        <p:selectOneMenu id="brandId" value="#{order1Controller.selected.brandId}" >
                            <f:selectItems value="#{brandEmersonController.itemsAvailableSelectOne}"
                                           var="brandIdItem"
                                           itemValue="#{brandIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{order1Controller.create}" value="#{bundle3.Save}" update="display,:Order1ListForm:datalist,:growl" oncomplete="handleSubmit(args,'Order1CreateDialog');"/>
                    <p:commandButton value="#{bundle3.Cancel}" onclick="Order1CreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/Admin/order1/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="Order1EditDlg" widgetVar="Order1EditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle3.EditOrder1Title}">
            <h:form id="Order1EditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{order1Controller.selected != null}">
                        <p:outputLabel value="#{bundle3.EditOrder1Label_id}" for="id" />
                        <p:inputText id="id" value="#{order1Controller.selected.id}" title="#{bundle3.EditOrder1Title_id}" required="true" requiredMessage="#{bundle3.EditOrder1RequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle3.EditOrder1Label_company}" for="company" />
                        <p:inputText id="company" value="#{order1Controller.selected.company}" title="#{bundle3.EditOrder1Title_company}" required="true" requiredMessage="#{bundle3.EditOrder1RequiredMessage_company}"/>
                        <p:outputLabel value="#{bundle3.EditOrder1Label_name}" for="name" />
                        <p:inputText id="name" value="#{order1Controller.selected.name}" title="#{bundle3.EditOrder1Title_name}" />
                        <p:outputLabel value="#{bundle3.EditOrder1Label_mobile}" for="mobile" />
                        <p:inputText id="mobile" value="#{order1Controller.selected.mobile}" title="#{bundle3.EditOrder1Title_mobile}" required="true" requiredMessage="#{bundle3.EditOrder1RequiredMessage_mobile}"/>
                        <p:outputLabel value="#{bundle3.EditOrder1Label_email}" for="email" />
                        <p:inputText id="email" value="#{order1Controller.selected.email}" title="#{bundle3.EditOrder1Title_email}" required="true" requiredMessage="#{bundle3.EditOrder1RequiredMessage_email}"/>
                        <p:outputLabel value="#{bundle3.EditOrder1Label_address}" for="address" />
                        <p:inputText id="address" value="#{order1Controller.selected.address}" title="#{bundle3.EditOrder1Title_address}" />
                        <p:outputLabel value="#{bundle3.EditOrder1Label_phone}" for="phone" />
                        <p:inputText id="phone" value="#{order1Controller.selected.phone}" title="#{bundle3.EditOrder1Title_phone}" required="true" requiredMessage="#{bundle3.EditOrder1RequiredMessage_phone}"/>
                        <p:outputLabel value="#{bundle3.EditOrder1Label_activityCompany}" for="activityCompany" />
                        <p:inputText id="activityCompany" value="#{order1Controller.selected.activityCompany}" title="#{bundle3.EditOrder1Title_activityCompany}" />
                        <p:outputLabel value="#{bundle3.EditOrder1Label_describtion}" for="describtion" />
                        <p:inputText id="describtion" value="#{order1Controller.selected.describtion}" title="#{bundle3.EditOrder1Title_describtion}" />
                        <p:outputLabel value="#{bundle3.EditOrder1Label_updatedAt}" for="updatedAt" />
                        <p:calendar id="updatedAt" pattern="MM/dd/yyyy HH:mm:ss" value="#{order1Controller.selected.updatedAt}" title="#{bundle3.EditOrder1Title_updatedAt}"  showOn="button"/>
                        <p:outputLabel value="#{bundle3.EditOrder1Label_createdAt}" for="createdAt" />
                        <p:calendar id="createdAt" pattern="MM/dd/yyyy HH:mm:ss" value="#{order1Controller.selected.createdAt}" title="#{bundle3.EditOrder1Title_createdAt}"  showOn="button"/>
                        <p:outputLabel value="#{bundle3.EditOrder1Label_productId}" for="productId" />
                        <p:selectOneMenu id="productId" value="#{order1Controller.selected.productId}" >
                            <f:selectItem itemLabel="#{bundle3.SelectOneMessage}"/>
                            <f:selectItems value="#{productController.itemsAvailableSelectOne}"
                                           var="productIdItem"
                                           itemValue="#{productIdItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle3.EditOrder1Label_cityId}" for="cityId" />
                        <p:selectOneMenu id="cityId" value="#{order1Controller.selected.cityId}" >
                            <f:selectItem itemLabel="#{bundle3.SelectOneMessage}"/>
                            <f:selectItems value="#{cityController.itemsAvailableSelectOne}"
                                           var="cityIdItem"
                                           itemValue="#{cityIdItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle3.EditOrder1Label_brandId}" for="brandId" />
                        <p:selectOneMenu id="brandId" value="#{order1Controller.selected.brandId}" >
                            <f:selectItem itemLabel="#{bundle3.SelectOneMessage}"/>
                            <f:selectItems value="#{brandEmersonController.itemsAvailableSelectOne}"
                                           var="brandIdItem"
                                           itemValue="#{brandIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{order1Controller.update}" value="#{bundle3.Save}" update="display,:Order1ListForm:datalist,:growl" oncomplete="handleSubmit(args, 'Order1EditDialog');"/>
                    <p:commandButton value="#{bundle3.Cancel}" onclick="Order1EditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/Admin/order1/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/Admin/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle3.ListOrder1Title}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="Order1ListForm">
                <p:panel header="#{bundle3.ListOrder1Title}">
                    <p:dataTable id="datalist" value="#{order1Controller.items}" var="item"
                                 selectionMode="single" selection="#{order1Controller.selected}"
                                 paginator="true"
                                 rowKey="#{item.id}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_company}"/>
                            </f:facet>
                            <h:outputText value="#{item.company}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_name}"/>
                            </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_mobile}"/>
                            </f:facet>
                            <h:outputText value="#{item.mobile}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_email}"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_address}"/>
                            </f:facet>
                            <h:outputText value="#{item.address}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_phone}"/>
                            </f:facet>
                            <h:outputText value="#{item.phone}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_activityCompany}"/>
                            </f:facet>
                            <h:outputText value="#{item.activityCompany}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_describtion}"/>
                            </f:facet>
                            <h:outputText value="#{item.describtion}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_updatedAt}"/>
                            </f:facet>
                            <h:outputText value="#{item.updatedAt}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_createdAt}"/>
                            </f:facet>
                            <h:outputText value="#{item.createdAt}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_productId}"/>
                            </f:facet>
                            <h:outputText value="#{item.productId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_cityId}"/>
                            </f:facet>
                            <h:outputText value="#{item.cityId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle3.ListOrder1Title_brandId}"/>
                            </f:facet>
                            <h:outputText value="#{item.brandId}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle3.Create}" actionListener="#{order1Controller.prepareCreate}" update=":Order1CreateForm" oncomplete="PF('Order1CreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle3.View}" update=":Order1ViewForm" oncomplete="PF('Order1ViewDialog').show()" disabled="#{empty order1Controller.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle3.Edit}" update=":Order1EditForm" oncomplete="PF('Order1EditDialog').show()" disabled="#{empty order1Controller.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle3.Delete}" actionListener="#{order1Controller.destroy}" update=":growl,datalist" disabled="#{empty order1Controller.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/Admin/order1/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="Order1ViewDlg" widgetVar="Order1ViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle3.ViewOrder1Title}">
            <h:form id="Order1ViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{order1Controller.selected != null}">
                        <h:outputText value="#{bundle3.ViewOrder1Label_id}"/>
                        <h:outputText value="#{order1Controller.selected.id}" title="#{bundle3.ViewOrder1Title_id}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_company}"/>
                        <h:outputText value="#{order1Controller.selected.company}" title="#{bundle3.ViewOrder1Title_company}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_name}"/>
                        <h:outputText value="#{order1Controller.selected.name}" title="#{bundle3.ViewOrder1Title_name}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_mobile}"/>
                        <h:outputText value="#{order1Controller.selected.mobile}" title="#{bundle3.ViewOrder1Title_mobile}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_email}"/>
                        <h:outputText value="#{order1Controller.selected.email}" title="#{bundle3.ViewOrder1Title_email}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_address}"/>
                        <h:outputText value="#{order1Controller.selected.address}" title="#{bundle3.ViewOrder1Title_address}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_phone}"/>
                        <h:outputText value="#{order1Controller.selected.phone}" title="#{bundle3.ViewOrder1Title_phone}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_activityCompany}"/>
                        <h:outputText value="#{order1Controller.selected.activityCompany}" title="#{bundle3.ViewOrder1Title_activityCompany}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_describtion}"/>
                        <h:outputText value="#{order1Controller.selected.describtion}" title="#{bundle3.ViewOrder1Title_describtion}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_updatedAt}"/>
                        <h:outputText value="#{order1Controller.selected.updatedAt}" title="#{bundle3.ViewOrder1Title_updatedAt}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle3.ViewOrder1Label_createdAt}"/>
                        <h:outputText value="#{order1Controller.selected.createdAt}" title="#{bundle3.ViewOrder1Title_createdAt}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle3.ViewOrder1Label_productId}"/>
                        <h:outputText value="#{order1Controller.selected.productId}" title="#{bundle3.ViewOrder1Title_productId}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_cityId}"/>
                        <h:outputText value="#{order1Controller.selected.cityId}" title="#{bundle3.ViewOrder1Title_cityId}"/>
                        <h:outputText value="#{bundle3.ViewOrder1Label_brandId}"/>
                        <h:outputText value="#{order1Controller.selected.brandId}" title="#{bundle3.ViewOrder1Title_brandId}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle3.Close}" onclick="Order1ViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>